Kibibit/kibibit-code-editor

app/models/fileService.js
app/models/folderService.js
app/routes/api.js
public/app/controllers/mainCtrl.js
public/app/views/pages/home.html
public/assets/sass/style.scss

Changed directory tree behavior on BE & FE to implement lazy loading (loading each directory when it is requested).
* Refactored `api.js` to two new files: `folderService.js` & `fileService.js`.
* Changed behavior of folderService get function to implement getting only the requested directory layer.
* New `folderService.js` sets the `type` attribute as the *file extension*.
* changed `directory-tree` to implement lazy loading using the new `folderService.get` function.
* Change file icon (and color) based on tree `type` attribute.
* On initialization, The initial `tmp_path` directory will be loaded (moved to a variable for convenience).
* `14 - output.name = 'Development';` is hard-coded. Needs to just get the directory name and **of course it needs to check that the path is actually a …

[Enhancement] Lazy loading tree

---

public/app/controllers/mainCtrl.js
public/app/services/eventManagerService.js
public/app/services/fileService.js
public/app/services/folderService.js
public/app/views/index.html

Incapsulated some $http request inside services
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/30)

[Massive Refactor] phase 2.0

---

gulpfile.js
public/assets/sass/_components/_sidebar.scss
public/assets/sass/_fonts.scss
public/assets/sass/_init.scss
public/assets/sass/style.scss

as a follow up to our massive refactoring, I'm encapsulating sass files by component. As we go on and re-do the `home.html`, we'll start to do more and more encapsulating of styles

Encapsulate styles

---

public/app/controllers/mainCtrl.js
public/assets/sass/_modal.scss

The modal part was just for fun.
But it helped me find the last `$scope` trail left in our code ^_^

remove last scope trail + basic modal style

---

.travis.yml
bower.json
gulpfile.js
karma.conf.js
package.json
test/hello.js

This adds testing frameworks to our sweet Kibibit Editor app.
Currently, this tests nothing really, but now at least pull request pass the travis tests I tried to integrate a few weeks ago :+1: 
Once ***real tests*** will be written, it will keep us from breaking the public app
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/42)

[Testing Framework] add testing and travis ci

---

.travis.yml
public/app/app.js

Add travis slack integration. so now we'll see if tests pass in our #general channel
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/43)

Slack travis integration

---

Procfile
gulpfile.js
package.json
public/app/views/index.html
server.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/50)

Should fail to submit pr

---

Procfile
gulpfile.js
package.json
public/app/views/index.html
server.js

Reverts Kibibit/kibibit-code-editor#50
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/51)

Revert "Should fail to submit pr"

---

server.js

This will allow Heroku to set the port
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/52)

[CI] make the port use the environment variable first

---

app.json

Maybe heroku needs this set by itself (although it looks like it is set to 3141 that way)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/54)

[CI] removing port number.

---

gulpfile.js

since hound will handle styling of pull requests
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/58)

trying without testing styling

---

.hound.yml
.pullapprove.yml
app.json
gulpfile.js
server.js

as suggested by Heroku support, I fixed some things to make PR demos work :+1: 
I'm excited! This is a **huge advancement with our deployment process!!!**
Now, we'll be able to compare the ***master branch demo** to the ***Pull Request demo*** to see what changed :dancer: :dancer: :dancer: 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/59)

[BUILD TOOLS] Cleaning up things for Heroku

---

bower.json
package.json

This was noticed due to the help of [![Dependencies Status](https://img.shields.io/gemnasium/Kibibit/kibibit-code-editor.svg)](https://gemnasium.com/Kibibit/kibibit-code-editor), powered by Gemnasium (check them out by clicking on the badge).
- VERSION 1.0.1
>BUG FIXES
- VERSION 1.0.0
>This is a landmark release - announcing public availability of version 1.0.0!
>>**NOTICE:** This is important since now it's a fully functional first version!
**NOTICE:** Since this is a much smaller jump in version, most of the changes are some bug fixes and updating its own dependencies :smile:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/63)

[dependencies] updated some dependencies to latest

---

bower.json
public/app/app.js
public/app/components/menuBar/menuBar.js
public/app/components/menuBar/menuBarTemplate.html
public/app/views/home.html
public/app/views/index.html

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/67)

re-introduce angular material

---

bower.json
public/app/app.js
public/app/components/menuBar/menuBarTemplate.html
public/app/controllers/mainCtrl.js
public/app/views/index.html

this connects to #10
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/70)

Add fullscreen action

---

public/assets/sass/style.scss

in order to show scrollbar for long names and short sidebar
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/74)

make tree width overflow the container

---

bower.json
package.json
public/app/components/menuBar/menuBarTemplate.html
public/app/views/index.html

- add icons to the `menu-bar` component.
> Basically, added the icons that already present in the demo (while replacing things for their kibibit uses).
I used the `angular-material` font icon set so now we have those usable as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/86)

add material icons

---

public/assets/sass/style.scss

just little style fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/98)

make scrollbar of tree align to the right of the modal

---

app/models/folderService.js

- make server return the correct name for the source directory [ resolves #104 ]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/105)

make server return the correct name for the source directory

---

public/app/views/index.html
public/assets/sass/style.scss

- Hide app's bootstrapping and load view gracefully [ resolves #106 ]
> need to try this remotely to check for network differences
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/107)

hide app loading

---

bower.json
public/app/views/index.html

replace to the older version [ Resolves #85 ]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kibibit/kibibit-code-editor/112)

replace ui-layout version

---

package.json
server.js

- implement `helmet.js` to protect our user's files from sniffing attacks and browser vulnerabilities [resolves #142]
> see more at https://github.com/helmetjs/helmet
====

[FEATURE] Add helmet for extra security

---

app/models/fileService.js
app/models/folderService.js
bower.json
public/app/views/index.html

- Add file tag component on server side to allow secondary icons on clients [ resolves #73 ]
> This will be served on a `GET` for folders (files inside it) and files (for code editor)
- update `ace.js` to latest version to expand `modelist` (see **More info**) [ resolves #140 ]
new additional modes:
```javascript
ABC:         ["abc"],
ADA:         ["ada|adb"],
C9Search:    ["c9search_results"],
Dockerfile:  ["^Dockerfile"],
Dummy:       ["dummy"],
DummySyntax: ["dummy"],
Eiffel:      ["e|ge"],
EJS:         ["ejs"],
Elixir:      ["ex|exs"],
Elm:         ["elm"],
Erlang:      ["erl|hrl"],
Fortran:     ["f|f90"],
Gcode:       ["gcode"],
Gitignore:   ["^.gitignore"],
Gobstones:   ["gbs"],
HTML_Elixir: ["eex|html.eex"],
Io:          ["io"],
Lean:        ["lean|hlean"],
Mask:        ["mask"], …
```

[FEATURE] File tags component

---

app/models/consoleService.js
app/models/fileService.js
app/models/folderService.js
app/models/userHomeDirectoryService.js
package.json
server.js

- make a function so that we won't repeat tags and times on each file [ resolves #4 ]

[REFACTOR] Make console component server

---

public/assets/sass/style.scss

- make arrow clickable in file tree [resolves #151]
====

[BUG] Make arrow clickable in file tree

---

app/models/downloadService.js
app/models/fileService.js
app/routes/api.js

Add download api to have better serving procedure for fonts.
The download file is just downloading an actual file.
the content of the request should be the file itself

[Feature] Add download file api

---

.travis.yml

quick PR to fix travis. if this passes the travis tests, I'm getting this in as is

[BUILD][BUG] Fix travis

---

public/app/components/menuBar/menuBarTemplate.html
public/app/components/searchProject/searchProject.js
public/app/components/searchProject/searchProjectTemplate.html
public/app/views/index.html
public/assets/sass/_components/_searchProject.scss
public/assets/sass/style.scss

- Add search project bar
> This doesn't do nothing for now. But we already have buttons that do nothing, so, for now, just to release this old branch, I'm submitting this :-)
There are some hound fixes I don't understand. I'll try and fix this later
>> Does nothing so no bug for now

Add search project for kibibit

---

bower.json

- change short synopsis I [resolves #00]
> additional info about this mission
- change short synopsis II (mission without additional info)
- change short synopsis III
(Free text here with additional photos, wikis, and additional needed information)
(reviewers ***shouldn't approve a PR without the next three checkboxs checked***)
>> Make sure there's an issue open about the change you did *(open one if there isn't)*. link this PR to that issue by writing `resolves #{{issue_number}}`. If this PR had several mission, link each issue in its parallel mission.
>> hound can be **pretty rough** at keeping our code clean and readable! make sure you format your code by running either `gulp format` or `gulp lint` and cleaning out all …

change Angular resolution to 1.5.8

---

bower.json
package.json
server.js

- add compression middleware to `express.js` [resolves #174]

[FEATURE] add compression middleware for express.js

---

bower.json
public/app/components/fullImageView/fullImageView.js
public/app/components/renderOnResize/renderOnResize.js
public/app/services/eventManagerService.js
public/app/views/index.html
public/assets/sass/_components/_viewByFile.scss
public/assets/sass/style.scss

- update views that needs resizing on sidebar resize [resolves #00]
- fix bugs in `eventManaterService` (mission without additional info)

[FEATURE] Update on resize sidebar

---

public/app/services/fileService.js
public/app/services/folderService.js
public/app/services/quotesService.js
public/app/services/settingsService.js
public/app/services/toastService.js

refactoring all service to same new syntax

[REFACTOR] Refactor all services

---

.gitignore
public/app/app.js
public/app/components/codeEditor/codeEditor.js
public/app/components/viewByFile/viewByFile.js
public/app/constants.js
public/app/services/draftsService.js
public/app/views/index.html

- Created drafts service that saves to and load from sessionStorage [connects #14 ]
- creates local drafts object on initiation and use it to provide drafts to the code editor
- implements get, save and delete draft functions
>> Make sure there's an issue open about the change you did *(open one if there isn't)*. link this PR to that issue by writing `resolves #{{issue_number}}`. If this PR had several mission, link each issue in its parallel mission.
>> hound can be **pretty rough** at keeping our code clean and readable! make sure you format your code by running either `gulp format` or `gulp lint` and cleaning out all the ***lint errors***. If you won't, you'll have a ***long conversation*** with hound :-)

[FEATURE] Add drafts

---

public/app/app.routes.js
public/app/components/menuBar/menuBar.js
public/app/components/renderOnResize/renderOnResize.js
public/app/services/authService.js
public/app/services/userService.js

Gonna keep these pull requests simple.

change all to array syntax for minification and uglify

---

bower.json
public/app/views/index.html

get them from bower instead of just having them statically in `lib\` folder

add ui-layout and ace.js through bower.js

---

bower.json
public/app/components/fileTree/fileTree.js

- [resolves #225 ]
- added $onInit life-cycle hook
- alphabetized function and variable names
`bindToController` pass it's attributes to the controller only after the controller initiated. 
so we got `undefined` for every variable we passed. 
using `$onInit` [lifecycle hook](https://docs.angularjs.org/guide/component) to extend the `option` variable with the `userOptions` variable solved the problem (the tree default mode is **file** and the projectFolder modal need **folder** mode) as well as the color theme problem.

[BUG] Open project modal

---

README.md

- change short synopsis I [resolves #00]
> additional info about this mission
- change short synopsis II (mission without additional info)
- change short synopsis III
(Free text here with additional photos, wikis, and additional needed information)
(reviewers ***shouldn't approve a PR without the next three checkboxs checked***)
>> Make sure there's an issue open about the change you did *(open one if there isn't)*. link this PR to that issue by writing `resolves #{{issue_number}}`. If this PR had several mission, link each issue in its parallel mission.
>> hound can be **pretty rough** at keeping our code clean and readable! make sure you format your code by running either `gulp format` or `gulp lint` and cleaning out all …

test pull request with github
